#!/usr/bin/env bash
# script containing commands to automatically configure a Ubuntu machine
sudo apt-get update -y
sudo apt-get install -y nginx

sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
service nginx restart
