#!/usr/bin/env bash
# displays the content of the file /etc/passwd
while read -r line
do
	user=$(echo "$line" | cut -d: -f1)
	uid=$(echo "$line" | cut -d: -f3)
	home=$(echo "$line" | cut -d: -f6)

	echo "$user:$uid:$home"
done < /etc/passwd
