#!/usr/bin/env bash
# displays the content of the current directory, Where only the part of the name after the first dash is displayed
for file in *
do
	if [ -f "$file" ] && [ "${file:0:1}" != "." ]
	then
		echo "${file#*-}"
	fi
done
