#!/usr/bin/env bash
# Bash script that configures an Ubuntu server:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8
cp /etc/hosts /etc/hosts.backup
sed -i 's/^127[0-9.]*\slocalhost/127.0.0.2 localhost/' /etc/hosts.backup
sed -i '$ a\8.8.8.8 facebook.com' /etc/hosts.backup
cp -f /etc/hosts.backup /etc/hosts
